[package]
name = "guilty"
version = "0.0.0"
edition = "2021"
description = "Actually nothing, but in the future, an api wrapper for Guilded !"
license = "GPL-3.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
